# Generated by Django 3.0.7 on 2020-11-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('tipo', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tareta de Identidad'), ('CE', 'Cedula de Extranjeria'), ('RC', 'Registro Civil')], max_length=5, verbose_name='Tipo de Identificacion')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cedula')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=5, verbose_name='Genero')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Registrar Datos Del Usuario',
                'verbose_name_plural': 'Registrar Datos De los Usuarios',
            },
        ),
    ]
