# Generated by Django 3.0.7 on 2020-11-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_conductor_tipotransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_aceite', models.DateField(verbose_name='Fecha Cambio De Aceite')),
                ('cambio_llanta', models.DateField(verbose_name='Fecha Cambio De Llantas')),
                ('observacion', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('tipo_transporte', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.TipoTransporte', verbose_name='Lista De Vehiculos')),
            ],
            options={
                'verbose_name': 'Registrar Datos Del Mantenimiento Del Vehiculo',
                'verbose_name_plural': 'Registrar Datos De los Mantenimientos De Los Vehiculos',
            },
        ),
    ]
