# Generated by Django 3.0.7 on 2020-11-29 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_tipotransporte_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(choices=[('CDR', 'I.E.Concentración DE Desarrollo Rural'), ('PLT', 'I.E.Pedro Leon Torres'), ('AMY', 'Alcaldia Municipal De Yacuanquer')], max_length=5, verbose_name='Institución')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('soat_exp', models.DateField(verbose_name='Fecha de Expedición Soat')),
                ('soat_ven', models.DateField(verbose_name='Fecha de Vencimiento Soat')),
                ('poliza_exp', models.DateField(verbose_name='Fecha de Expedición Poliza')),
                ('poliza_ven', models.DateField(verbose_name='Fecha de Vencimiento Poliza')),
                ('tecno_mecanico_exp', models.DateField(verbose_name='Fecha de Expedición Tecnico Mecanico')),
                ('tecno_mecanico_ven', models.DateField(verbose_name='Fecha de Vencimiento Tecnico Mecanico')),
                ('id_conductor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Conductor', verbose_name='Conductores')),
                ('id_mantenimiento', models.ManyToManyField(to='agenda.Mantenimiento')),
                ('id_transporte', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.TipoTransporte', verbose_name='Lista De Vehiculos')),
            ],
            options={
                'verbose_name': 'Registrar Datos Del Vehiculo',
                'verbose_name_plural': 'Registrar Datos De los Vehiculos',
            },
        ),
    ]
