# Generated by Django 3.0.7 on 2020-11-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_agenda_inicio', models.DateField(verbose_name='Asignar Turno En La Agenda')),
                ('turno_agenda_final', models.DateField(verbose_name='Asignar Turno En La Agenda')),
                ('hora_inicio', models.DateTimeField(verbose_name='Asignar Hora De Inicio')),
                ('hora_final', models.DateTimeField(verbose_name='Asignar Hora Final')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('costo', models.BigIntegerField(verbose_name='Costo Total')),
                ('id_transporte', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.TipoTransporte', verbose_name='Lista De Vehiculos')),
                ('id_usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario', verbose_name='Lista De Usuarios')),
            ],
            options={
                'verbose_name': 'Registrar Datos Agenda',
                'verbose_name_plural': 'Registrar Datos En la Agenda',
            },
        ),
    ]
