# Generated by Django 3.0.7 on 2020-11-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='turno_agenda_final',
            field=models.DateTimeField(verbose_name='Asignar Turno Final'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='turno_agenda_inicio',
            field=models.DateTimeField(verbose_name='Asignar Turno De Inicio'),
        ),
    ]
